"""Build the dependency-free FT PVT. LIMITED website. Python 3.12+."""
from pathlib import Path
from html import escape
import argparse
import json
import re
import shutil
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent
parser = argparse.ArgumentParser()
parser.add_argument('--site-url', help='Verified HTTPS origin, e.g. your own domain')
parser.add_argument('--production', action='store_true', help='Require a verified production origin')
args = parser.parse_args()
config = json.loads((ROOT / 'site.config.json').read_text(encoding='utf-8'))
origin = (args.site_url or config['site_url']).rstrip('/')
if origin and (urlparse(origin).scheme != 'https' or not urlparse(origin).netloc or urlparse(origin).path not in ('', '/') or urlparse(origin).query or urlparse(origin).fragment):
    raise SystemExit('site_url must be an HTTPS origin without a path, query or fragment.')
if args.production and not origin:
    raise SystemExit('Production build requires the owner-confirmed domain in site.config.json or --site-url.')
download = config['download_url']
if download and (urlparse(download).scheme != 'https' or not urlparse(download).netloc):
    raise SystemExit('download_url must be a verified HTTPS download or store URL.')
OUT = ROOT / 'dist'
OUT.mkdir(exist_ok=True)
shutil.copytree(ROOT / 'assets', OUT / 'assets', dirs_exist_ok=True)
(OUT / '.nojekyll').write_text('', encoding='utf-8')
COMPANY = 'FT PVT. LIMITED'
EMAIL = 'kcorporation70@gmail.com'
APP = '/apps/all-document-reader/'
POLICY = APP + 'privacy/'
CONTACT = '/contact/'
esc = lambda value: escape(str(value), quote=True)

def button(label, url, secondary=False):
    return f'<a class="btn{" secondary" if secondary else ""}" href="{esc(url)}">{label}</a>'

def get_app():
    return button('Get All Document Reader <span aria-hidden="true">↗</span>' if download else 'Ask about availability <span aria-hidden="true">↗</span>', download or f'mailto:{EMAIL}?subject=All%20Document%20Reader%20Availability')

def bread(items):
    return '<nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a>' + ''.join(f'<span aria-hidden="true">/</span><a href="{url}">{label}</a>' if url else f'<span aria-hidden="true">/</span><span aria-current="page">{label}</span>' for label,url in items) + '</nav>'

def hero(label, title, desc, crumbs=None):
    return f'<section class="page-hero"><div class="wrap">{bread(crumbs) if crumbs else ""}<span class="eyebrow">{label}</span><h1>{title}</h1><p class="lead">{desc}</p></div></section>'

def panel():
    return f'''<article class="product-panel" aria-label="All Document Reader overview"><div class="panel-top"><span>Our application</span><span>Android</span></div><h2 class="panel-heading">All Document<small>Reader.</small></h2><p class="panel-desc">From the first page to the final detail. Your everyday documents, within reach.</p><div class="product-capabilities"><div class="capability"><strong>Read</strong><span>PDF &amp; office files</span></div><div class="capability"><strong>Find</strong><span>Documents on your device</span></div><div class="capability"><strong>Organize</strong><span>A simpler reading routine</span></div></div><div class="panel-bottom"><span class="tag">Made for everyday reading</span><a href="{APP}">Meet the app <span aria-hidden="true">↗</span></a></div></article>'''

def cards(items):
    return '<div class="grid3">' + ''.join(f'<article class="card"><span class="number">0{i}</span><h3>{title}</h3><p>{body}</p></article>' for i,(title,body) in enumerate(items,1)) + '</div>'

FEATURES = [('Open the document you need','Read PDFs, Word documents, spreadsheets, presentations and text files in one app. Spend less time switching between tools.'),('Find files on your device','Locate supported documents through the file access you choose to grant. Bring everyday reading into one familiar place.'),('Keep reading straightforward','Open, read and organize documents with a focused mobile workflow—whether you are reviewing work or catching up on personal files.')]

def cta():
    return f'<section class="section"><div class="wrap"><div class="cta"><div><h2>A little help goes a long way.</h2><p>Questions about a file, app permissions or your subscription? Get in touch with our team.</p></div>{button("Contact us <span aria-hidden=\"true\">↗</span>",CONTACT)}</div></div></section>'

def faq():
    items = [
      ('Which file formats can I read?', 'All Document Reader supports PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX and TXT. File complexity, encryption or damage can affect how an individual file opens or displays.'),
      ('Is All Document Reader available for iPhone?', 'All Document Reader is an Android app. We have not announced an iPhone version. This website works on Android, iPhone, tablet and desktop browsers.'),
      ('Are my documents uploaded to your servers?', f'Core document reading takes place on your device. FT PVT. LIMITED does not operate a document-upload server for the app. Third-party services handle certain technical, analytics and advertising information. Read the <a href="{POLICY}">app privacy policy</a> for the full details.'),
      ('Do I need an account?', 'An FT PVT. LIMITED account is not required for the main document-reading features. File access depends on the permissions you grant on your device.'),
      ('Does the app contain advertisements?', 'The free version displays advertising. A paid subscription provides an ad-free experience; non-advertising services such as analytics may remain active. Review the price and billing details shown in Google Play before subscribing.'),
      ('What if a document will not open?', f'Check that the file uses a supported format, has downloaded completely and is accessible to the app. If the issue continues, <a href="{CONTACT}">contact support</a> with the file extension, app version and Android version. Do not send confidential documents.')
    ]
    return '<div class="faq">' + ''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items) + '</div>'

pages = {}
def add(route, title, desc, body, active='', noindex=False):
    pages[route] = (title,desc,body,active,noindex)

home = f'''<section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">FT PVT. LIMITED · Everyday software</span><h1>Less searching.<br>More <span>reading.</span></h1><p class="lead">Meet All Document Reader. A simpler way to open, read and organize the documents you need on your Android device.</p><div class="actions">{button('Explore the app <span aria-hidden="true">↗</span>',APP)}<a class="text-link" href="/about/">Get to know us</a></div><p class="micro">PDF, documents, spreadsheets, presentations &amp; text.</p></div>{panel()}</div></section><div class="wrap strip"><div class="strip-item"><span>01 /</span> Everyday document reading</div><div class="strip-item"><span>02 /</span> Designed for Android</div><div class="strip-item"><span>03 /</span> No company account required</div></div><section class="section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Small details. Useful differences.</span><h2>Make room for what<br>you need to read.</h2></div><p>A report for work. Notes for class. A document from home. Keep the task simple, wherever the day takes you.</p></div>{cards(FEATURES)}</div></section><section class="section band"><div class="wrap split"><div><span class="eyebrow">Our approach</span><h2>Useful software.<br>A clear purpose.</h2><p>At FT PVT. LIMITED, our focus is All Document Reader: a practical tool for the documents that are part of daily life.</p><div class="actions"><a class="text-link" href="/about/">More about FT PVT. LIMITED ↗</a></div></div><ul class="rule-list"><li><strong>Start with the everyday</strong>Make finding and reading a document feel straightforward.</li><li><strong>Explain the essentials</strong>Keep product information, permissions and privacy easy to find.</li><li><strong>Stay within reach</strong>Offer a direct route to support when you need a hand.</li></ul></div></section>{cta()}'''
add('/', 'FT PVT. LIMITED | Everyday document reading', 'Discover All Document Reader by FT PVT. LIMITED. Open, read and organize PDF, office and text documents on Android, with clear privacy and support information.', home, 'home')

apps = hero('Our product','One app. Everyday possibilities.','All Document Reader brings your document-reading routine into one focused Android experience.', [('Apps',None)]) + f'''<section class="section band"><div class="wrap product-feature">{panel()}<div><span class="eyebrow">Documents · Android</span><h2>All Document Reader</h2><p>Read the files that keep your day moving—from PDFs and Word documents to spreadsheets, presentations and plain text.</p><ul class="rule-list"><li><strong>One place to read</strong>Support for eight everyday file extensions.</li><li><strong>Files within reach</strong>Locate and organize supported documents on your device.</li></ul><div class="actions">{button('Explore All Document Reader',APP)}<a href="{POLICY}">App privacy</a></div></div></div></section>{cta()}'''
add('/apps/','Apps | All Document Reader | FT PVT. LIMITED','Explore All Document Reader, the Android document-reading app from FT PVT. LIMITED. View supported formats, features, privacy information and support.',apps,'apps')

formats = ''.join(f'<span class="format">{esc(fmt)}</span>' for fmt in config['supported_formats'])
app = hero('Documents · Made for Android','All Document Reader','Your day has enough moving parts. Opening a document should be the easy one. Read and organize the files you need in a focused Android app.', [('Apps','/apps/'),('All Document Reader',None)]) + f'''<div class="wrap"><div class="actions">{get_app()}{button('Read privacy policy',POLICY,True)}</div><p class="micro">{'Use the official listing for current availability and pricing.' if download else 'Contact us for the current official download link and availability.'}</p><nav class="details-nav" aria-label="On this page"><a href="#features">Features</a><a href="#formats">Supported formats</a><a href="#privacy">Privacy &amp; security</a><a href="#faq">Common questions</a></nav></div><section class="section" id="features"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Built around your files</span><h2>From finding a file<br>to getting things done.</h2></div></div>{cards(FEATURES)}</div></section><section class="section band" id="formats"><div class="wrap split"><div><span class="eyebrow">Supported formats</span><h2>Different files.<br>One familiar place.</h2><p>Work documents, study material and everyday notes all have a place in your reading routine.</p></div><div><div class="format-list">{formats}</div><p>Open PDF files, Word documents, Excel spreadsheets, PowerPoint presentations and plain text. Compatibility can vary with encryption, embedded content, file damage and complex formatting.</p><p class="micro">Need help with a particular file? <a href="/contact/">Tell us its extension</a>.</p></div></div></section><section class="section" id="privacy"><div class="wrap split"><div><span class="eyebrow">Privacy &amp; security</span><h2>Your documents.<br>Clear information.</h2><p>Core document reading happens on your device. FT PVT. LIMITED does not receive or store the contents of documents opened through the app’s reading features.</p><div class="actions">{button('Understand app privacy',POLICY,True)}</div></div><ul class="rule-list"><li><strong>You manage file access</strong>Review and change app permissions in your Android settings.</li><li><strong>No company account to create</strong>The main document-reading features do not require an FT PVT. LIMITED account.</li><li><strong>Third-party services, explained</strong>Advertising, analytics, diagnostics and other services may process technical information. Our app policy explains the differences and your choices.</li></ul></div></section><section class="section band" id="faq"><div class="wrap"><div class="section-head"><div><span class="eyebrow">A few useful answers</span><h2>Before you open your next file.</h2></div></div>{faq()}</div></section>{cta()}'''
add(APP,'All Document Reader for Android | FT PVT. LIMITED','Read PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX and TXT files with All Document Reader for Android. Explore features, privacy, availability and support.',app,'apps')

about = hero('About FT PVT. LIMITED','Everyday software,<br>with a practical purpose.','We build around a familiar need: making it easier to work with the documents on your phone.', [('About',None)]) + f'''<section class="section band"><div class="wrap split"><div><span class="eyebrow">Our focus</span><h2>Make the next task<br>a little simpler.</h2></div><div><p>FT PVT. LIMITED is the company behind All Document Reader. Our focus is a straightforward mobile experience for opening, reading and organizing supported documents.</p><p>We believe product information should be just as accessible as the product itself. That is why you can find features, supported formats, privacy information and a direct support contact together on this website.</p><div class="actions">{button('Discover All Document Reader',APP)}</div></div></div></section><section class="section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">What guides us</span><h2>Keep the useful things in focus.</h2></div></div>{cards([('Clarity','Explain what the app does, the formats it supports and where to get help.'),('Practicality','Build around everyday reading, with a clear path from finding a file to opening it.'),('Transparency','Make permissions, third-party services and privacy choices easy to understand.')])}</div></section>{cta()}'''
add('/about/','About FT PVT. LIMITED | The team behind All Document Reader','Learn about FT PVT. LIMITED, the company behind All Document Reader, and our focus on practical document reading, clear information and accessible support.',about,'about')

contact = hero('Contact','Let’s make it clearer.','Need help with All Document Reader, have a product question or want to reach the company? Email our team directly.', [('Contact',None)]) + f'''<section class="section"><div class="wrap support-grid"><article class="card"><span class="eyebrow">Your direct line</span><h2>Talk to FT PVT. LIMITED</h2><p>For app support, availability and company enquiries.</p><a class="contact-email email" href="mailto:{EMAIL}">{EMAIL}</a>{button('Write an email <span aria-hidden="true">↗</span>',f'mailto:{EMAIL}?subject=All%20Document%20Reader%20Support')}<p class="micro">Opens your email app. You can also copy the address above into your preferred email service.</p></article><article class="card"><span class="eyebrow">Help us help you</span><h2>A few details make a difference.</h2><ul class="rule-list"><li><strong>Tell us what happened</strong>Include the action you tried and any error message.</li><li><strong>Share the essentials</strong>Your Android version, app version and file extension are a useful starting point.</li><li><strong>Keep private files private</strong>Please do not email passwords, payment details or confidential documents.</li></ul></article></div></section><section class="section band"><div class="wrap split"><div><h2>A privacy question?</h2><p class="lead">Read how information is handled or contact us about your data.</p></div><div><p>For privacy and deletion requests, email us with the subject “All Document Reader Privacy Request.” Tell us what information your request concerns.</p><div class="actions">{button('App privacy policy',POLICY,True)}<a href="/privacy-policy/">Website privacy</a></div></div></div></section>'''
add('/contact/','Contact FT PVT. LIMITED | All Document Reader support','Contact FT PVT. LIMITED at kcorporation70@gmail.com for All Document Reader support, download availability, company enquiries and privacy requests.',contact,'contact')

support = hero('All Document Reader support','A clearer path to an answer.','Find help with documents, permissions, subscriptions and privacy—or contact us directly.', [('Support',None)]) + f'''<section class="section"><div class="wrap">{faq()}<div class="actions">{button('Contact support','/contact/')}<a href="{POLICY}#choices">Privacy and deletion choices</a></div></div></section>'''
add('/support/','All Document Reader Support | FT PVT. LIMITED','Find answers about supported documents, Android permissions, advertisements, subscriptions and data choices for All Document Reader.',support)

def legal_body(label,title,intro,sections,crumbs):
    nav = '<aside class="contents"><nav aria-label="Page contents"><h2>On this page</h2><ul>' + ''.join(f'<li><a href="#{sid}">{esc(heading)}</a></li>' for sid,heading,content in sections) + '</ul></nav></aside>'
    content = '<div class="legal-content">' + ''.join(f'<article id="{sid}"><h2>{heading}</h2>{content}</article>' for sid,heading,content in sections) + '</div>'
    return hero(label,title,intro,crumbs) + f'<div class="wrap"><p class="legal-meta">Last updated: September 25, 2026 · {COMPANY}</p></div><section class="section"><div class="wrap legal-layout">{nav}{content}</div></section>'

web_privacy = [
 ('scope','1. Scope',f'<p>This policy describes information handled when you visit the FT PVT. LIMITED website or contact us. Use of All Document Reader is covered by its separate <a href="{POLICY}">app privacy policy</a>.</p>'),
 ('information','2. Information we receive','<p>If you email us, we receive your email address, message and any attachments you choose to send. Please share only what is needed for your enquiry.</p><p>The hosting and email providers used to deliver this website and respond to messages may process technical data, such as IP address, browser information, request time and security logs.</p>'),
 ('cookies','3. Cookies and analytics','<p>This website does not include advertising, analytics trackers, account registration or a document-upload feature. Its own code does not set cookies or use browser storage. Your browser and our hosting or email providers may process technical information needed to deliver their services.</p>'),
 ('purpose','4. Use and sharing','<p>We use support correspondence to respond to your request, investigate problems, maintain relevant records and protect against misuse. Relevant service providers process information needed to deliver hosting and email. We may disclose information when required by law or to protect lawful rights and safety.</p><p>We do not sell support correspondence. We do not use the website to collect the documents stored on your device.</p>'),
 ('retention','5. Retention and security','<p>We retain correspondence as reasonably necessary to handle the enquiry, resolve disputes, prevent abuse and meet applicable obligations. Provider logs follow the provider’s own retention practices. No transmission or storage system is completely secure; avoid sending sensitive files by email.</p>'),
 ('rights','6. Your choices and requests',f'<p>You may contact <a href="mailto:{EMAIL}">{EMAIL}</a> to request access, correction or deletion of personal information held directly by us. Applicable rights and exceptions depend on your location and the law. We may need to verify a request before acting.</p><p>Service providers may process data outside your country under their own terms and safeguards. Where applicable, you may raise a concern with your local data-protection authority.</p>'),
 ('children','7. Children','<p>This website is intended for general product information and support. If you believe a child has sent personal information to us, contact us so we can review and respond.</p>'),
 ('links','8. External links','<p>Links to external websites and email services are governed by their operators’ policies. This website’s policy does not replace the privacy disclosures for All Document Reader or its third-party services.</p>'),
 ('changes','9. Updates and contact',f'<p>We will update the date on this page when this policy changes. For website privacy questions, contact FT PVT. LIMITED at <a href="mailto:{EMAIL}">{EMAIL}</a>.</p>')
]
add('/privacy-policy/','Website Privacy Policy | FT PVT. LIMITED','Read how the FT PVT. LIMITED website handles support emails, technical information, privacy requests and links to All Document Reader app disclosures.',legal_body('Website information','Privacy Policy','How information is handled when you visit our website or get in touch.',web_privacy,[('Privacy Policy',None)]))

terms = [
 ('scope','1. About these terms',f'<p>These Terms &amp; Conditions apply to the FT PVT. LIMITED website and All Document Reader. By using them, you agree to these terms where permitted by applicable law. If you do not agree, stop using the services. Contact us at <a href="mailto:{EMAIL}">{EMAIL}</a> with questions.</p>'),
 ('use','2. Permitted use','<p>You may use the website for information and the app for its intended document-reading functions, subject to applicable law and any additional terms shown at purchase or installation. Do not interfere with the services, attempt unauthorized access, distribute malicious material or infringe another person’s rights.</p><p>Our software, website design and original content remain protected by applicable intellectual-property rights. These terms do not transfer ownership to you.</p>'),
 ('files','3. Your files and device','<p>You keep ownership of your documents. Only access files you have the right to use. You control the permissions granted to the app and are responsible for maintaining copies of important files. Reading and display can vary with device capability, file format, encryption and file condition.</p><p>All Document Reader is not a backup service. The main document-reading functions do not require an FT PVT. LIMITED account.</p>'),
 ('payments','4. Advertising and subscriptions','<p>The free app displays advertisements. A paid subscription provides an ad-free experience. The price, billing period, renewal and any trial terms shown in Google Play at purchase govern your subscription. Do not assume that uninstalling the app cancels a subscription.</p><p>Manage or cancel purchases through your Google Play account. Refund requests follow applicable store rules and consumer law. See <a href="https://support.google.com/googleplay/answer/7018481">Google Play’s subscription guidance</a>. FT PVT. LIMITED does not directly collect your full payment-card number.</p>'),
 ('privacy','5. Privacy and third parties',f'<p>Read the <a href="/privacy-policy/">website privacy policy</a> and the <a href="{POLICY}">All Document Reader privacy policy</a> for information about permissions and processing. Third-party services and external links have their own terms. An ad-free subscription does not necessarily disable analytics or other non-advertising services.</p>'),
 ('availability','6. Availability and changes','<p>Features, availability and compatibility may change. We may update, suspend or discontinue parts of the services, subject to applicable obligations and any terms attached to a purchase. We do not promise uninterrupted availability or that every document will display identically on every device.</p>'),
 ('responsibility','7. Responsibility and consumer rights','<p>Use the services with reasonable care. To the extent permitted by applicable law, the services are provided without a guarantee that they will be error-free or meet every individual requirement. Nothing in these terms excludes rights, remedies or liabilities that cannot lawfully be excluded, including applicable consumer protections.</p><p>If a problem arises, contact us with the relevant details so we can review it. These terms do not impose a particular court or waive mandatory protections that apply where you live.</p>'),
 ('updates','8. Updates and contact',f'<p>We may revise these terms to reflect changes to the services or applicable requirements. The date above identifies the latest version. For questions or concerns, email <a href="mailto:{EMAIL}">{EMAIL}</a>.</p>')
]
add('/terms-and-conditions/','Terms & Conditions | FT PVT. LIMITED','Review terms for the FT PVT. LIMITED website and All Document Reader, including permitted use, files, subscriptions, third parties and consumer rights.',legal_body('Use of our services','Terms &amp; Conditions','The terms that apply to this website and All Document Reader.',terms,[('Terms & Conditions',None)]))

# Company-specific app disclosures are preserved from the supplied target policy.
policy_sections = json.loads((ROOT / 'content/app-privacy.json').read_text(encoding='utf-8'))
add(POLICY,'All Document Reader Privacy Policy | FT PVT. LIMITED','Learn how All Document Reader handles local documents, permissions, Firebase, advertising, subscriptions, retention and your privacy choices.',legal_body('All Document Reader','App Privacy Policy','How FT PVT. LIMITED handles information when you use All Document Reader for Android.',policy_sections,[('Apps','/apps/'),('All Document Reader',APP),('Privacy',None)]))

add('/404.html','Page not found | FT PVT. LIMITED','This page could not be found. Return to FT PVT. LIMITED or explore All Document Reader.',f'<div class="wrap"><section class="not-found"><span class="eyebrow">404 · Page not found</span><h1>Let’s get you<br>back on track.</h1><p>The page may have moved, or the address may be incorrect. Find All Document Reader or return to the homepage.</p><div class="actions">{button("Back to home","/")}{button("Explore the app",APP,True)}</div></section></div>',noindex=True)

def render(route,title,desc,body,active,noindex):
    nav = ''.join(f'<a href="{url}"{(" aria-current=\"page\"" if active == key else "")}{(" class=\"nav-contact\"" if key == "contact" else "")}>{label}</a>' for key,label,url in [('home','Home','/'),('apps','Our app','/apps/'),('about','About','/about/'),('contact','Contact us','/contact/')])
    canonical = f'<link rel="canonical" href="{esc(origin+route)}"><meta property="og:url" content="{esc(origin+route)}">' if origin and not noindex else ''
    robots = '<meta name="robots" content="noindex,follow">' if noindex or not origin else '<meta name="robots" content="index,follow">'
    schema = {'@context':'https://schema.org','@type':'Organization','name':COMPANY,'email':EMAIL}
    if origin: schema['url']=origin+'/'
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}">{robots}{canonical}<meta name="theme-color" content="#100e1c"><meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:site_name" content="{COMPANY}"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(desc)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{esc(title)}"><meta name="twitter:description" content="{esc(desc)}"><link rel="icon" type="image/svg+xml" href="/assets/favicon.svg"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script><script type="application/ld+json">{json.dumps(schema)}</script></head><body><a class="skip" href="#main" tabindex="0">Skip to content</a><header class="header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="FT PVT. LIMITED home"><span class="brand-mark" aria-hidden="true">FT</span>{COMPANY}</a><button class="menu" type="button" aria-controls="primary-nav" aria-expanded="false">Menu</button><nav class="nav" id="primary-nav" aria-label="Primary navigation">{nav}</nav></div></header><main id="main" tabindex="-1">{body}</main><footer class="footer"><div class="wrap"><div class="footer-grid"><div class="footer-intro"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">FT</span>{COMPANY}</a><p>Practical software for everyday documents.<br>The company behind All Document Reader.</p><a class="email" href="mailto:{EMAIL}">{EMAIL}</a></div><nav class="footer-nav" aria-label="Company links"><strong>Explore</strong><a href="/apps/">Our app</a><a href="{APP}">All Document Reader</a><a href="/about/">About us</a><a href="/contact/">Contact</a><a href="/support/">Support</a></nav><nav class="footer-nav" aria-label="Legal links"><strong>The details</strong><a href="/privacy-policy/">Website privacy</a><a href="{POLICY}">App privacy</a><a href="/terms-and-conditions/">Terms &amp; Conditions</a></nav></div><div class="footer-bottom"><span>© 2026 {COMPANY}. All rights reserved.</span><span>Thoughtfully simple. Purposefully useful.</span></div></div></footer></body></html>'''

for route,data in pages.items():
    dest = OUT / (route.lstrip('/') if route.endswith('.html') else route.lstrip('/')+'index.html')
    dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text(render(route,*data),encoding='utf-8')

for old,new in [('/privacy/','/privacy-policy/'),('/terms/','/terms-and-conditions/')]:
    dest=OUT/old.strip('/')/'index.html';dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><meta http-equiv="refresh" content="0;url={new}"><title>Page moved | FT PVT. LIMITED</title><link rel="stylesheet" href="/assets/site.css"></head><body><main class="wrap not-found"><h1>This page has moved.</h1><p><a href="{new}">Continue to {"Privacy Policy" if old == "/privacy/" else "Terms &amp; Conditions"}</a></p></main></body></html>',encoding='utf-8')

# A valid development sitemap is included; production build replaces its origin.
sitemap_origin = origin or 'http://localhost:4173'
routes = [r for r,data in pages.items() if not data[-1]]
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{esc(sitemap_origin+r)}</loc></url>\n' for r in routes)+'</urlset>\n',encoding='utf-8')
(OUT/'robots.txt').write_text('User-agent: *\n'+('Allow: /\nSitemap: '+origin+'/sitemap.xml\n' if origin else 'Disallow: /\n# Preview build: configure your verified domain and rebuild for production.\n'),encoding='utf-8')
(OUT/'_redirects').write_text('/privacy/ /privacy-policy/ 301\n/terms/ /terms-and-conditions/ 301\n',encoding='utf-8')
(OUT/'_headers').write_text('/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: default-src \'self\'; script-src \'self\'; style-src \'self\'; img-src \'self\' data:; font-src \'self\'; connect-src \'self\'; object-src \'none\'; base-uri \'self\'; frame-ancestors \'none\'; form-action \'none\'\n',encoding='utf-8')
print(f'Built {len(pages)} pages and 2 compatibility redirects in {OUT}')
print('Production metadata enabled: '+origin if origin else 'Preview mode: no invented domain. Set site_url and run build.py --production before publishing.')
